### ISSUE TITLE
Sorry, this page isn't available.

### ISSUE THREAD

**Issue by thistehneisen** [pixelfed/support#12]
I've followed all the installation steps, but can't get https://www.pixelfed.me/ any further than this error.

**Comment by thistehneisen** [comment]
Still no resolve for this.

**Comment by efelon** [comment]
Can you provide more details about your system setup?

- OS
- webserver version and configuration
- database version
- reverse proxy configuration (if used)
- pixelfed version and .env content

Simple things to (re)check:
- [ ] Update your installation to dev (I've seen you are on 0.10.5).
 The hard way would be:  In you pixelfed folder:
 - **DO A BACKUP**
 - Hard reset to dev:
```
git fetch --all
git reset --hard origin/dev
git pull origin dev
git checkout dev
```
 - Restore your .env (I recommend to start with the fresh .env.example
- [ ] Do all the pre-requisites have the correct version and are in place
https://docs.pixelfed.org/installing-pixelfed/prerequisites.html#http-web-server
e.g.
PHP >= 7.3
MySQL (5.7+)
MariaDB (10.2.7+ -- 10.3.5+ recommended)
PostgreSQL (10+)
 - [ ] Are the permissions and ownership set correctly for the pixelfed folder
- [ ] Is the URL correct for these:
```
APP_URL=http://localhost
APP_DOMAIN="localhost"
ADMIN_DOMAIN="localhost"
SESSION_DOMAIN="localhost"
TRUST_PROXIES="*"
```
- [ ] Are the database credentials correct
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=pixelfed
DB_USERNAME=pixelfed
DB_PASSWORD=pixelfed
```
- [ ] Is the horizon service running
e.g. https://docs.pixelfed.org/installing-pixelfed/postinstall.html#using-systemd
- [ ] Is there an admin user setup (not sure if this is relevant)

**Comment by gigq** [comment]
I know this is an old issue but this might help someone else that has the same problem I had and found this via google.

I had decided to change my domain name when originally setting up the server (pixel subdomain instead of pixelfed).  The .env still had the old pixelfed subdomain however.  Changing this still didn't fix it but I had forgotten to reset the caches as explained in the install tutorial:

```
php artisan config:cache
php artisan route:cache
php artisan view:cache
```

After running these with the correct domain in .env file it no longer showed the error page.
